--- # yamal script for installing httpd package and enabled it and restart it.

- hosts: webserver
  user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

# Declearing variables through different ways: 
  vars: 
    script_version: httpd_el_0.0rl
  vars_files: 
  - /home/ansible/ansible/playbook/conf/webserver.yml
  - /home/ansible/ansible/playbook/conf/database.yml
  vars_prompt: 
   - name: ansible_version
     prompt: The ansible version is

  tasks: 
   - name: Installing httpd and restarting service it is it not present and not restarting again if it is already installed.
     action: yum name=httpd state=installed 
     notify: restart httpd

  handlers: 
   - name: restart httpd
     action: service name=httpd state=restarted enabled=yes

  
