--- # Lookup module 

- hosts: database
  user: ansible
  sudo: yes
  gather_facts: no
  connection: ssh

  tasks:
   - debug: msg="This is the value of HOME variable is:= {{ lookup('env','HOME')}} for host {{ lookup('env','HOSTNAME') }} The ssh client detail is {{ lookup('env','SSH_CLIENT') }}" 

