--- # installing package using loop

- hosts: linuxA
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks: 
   - name: Installing httpd, lynx and telnet package
     yum: 
         name: "{{ item.name }}"
         state: present
     with_items: 
        - { name: 'httpd' }
        - { name: 'lynx' }
        - { name: 'telnet' }

   - name: Restarting sercices
     service:
        state: restarted
        enabled: yes
