--- # describing tags

- hosts: linuxA
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks: 
   - name: Installing telnet and lynx packages
     yum: pkg={{ item }} state=latest
     with_items: 
        - telnet
        - lynx
     tags: 
      - packages


   - name: verifying telnet service
     raw: yum list installed | grep telnet > /home/ansible/pkg.log
     tags: 
       - verify
