--- # Creating user using loop

- hosts: linuxA 
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks: 
   - name: adding user to the remote server using loop
     user: 
       name: "{{ item }}"
       password: AspectSoftware123$
       home: /home/{{ item }}2
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: /home/{{ item }}2/.ssh/id_rsa
       ssh_key_type: rsa
     with_items: 
       - user1
       - user2
       - user3
       - user4
   - name: Verfing users
     command: cat /etc/passwd 
     register: result
   - debug: var=result



   
