--- # until

- hosts: linuxA
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  
  tasks: 
    - name: installing HTTPD service in RHEL family
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"

    
    - name: installing Apache package in Dabian family 
      raw: apt-get install -y apache2
      when: ansible_os_family == "Debian"

    - name: getting status  httpd service
      command: systemctl status httpd
      register: result
      until: result.stdout.find ( "active (running)" ) != -1
      retries: 5
      delay: 5
