--- # Function

- hosts: linuxA
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes

  vars: 
   - include: variables/variables.yml

  tasks: 
   - include: packages/packages.yml
   - include: commands/commands.yml
  handlers: 
   - include: handlers/handlers.yml 
